# Generated by Django 4.2.6 on 2023-10-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='paragraphread',
        ),
    ]
