# Generated by Django 4.2.6 on 2023-10-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_description_service_paragraphread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('admin', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('admin', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
