# Generated by Django 4.2.6 on 2023-10-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('icon flaticon-houses', 'icon flaticon houses'), ('icon flaticon-living-room', 'icon flaticon living room')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
