# Generated by Django 4.2.6 on 2023-10-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(blank=True, choices=[('', 'Services '), ('Architectural Design', 'Architectural Design'), ('Interior Design and Fit-out Works', 'Interior Design and Fit-out Works'), ('3D Visualization and Graphics', '3D Visualization and Graphics'), ('Gypsum/Plaster Board/Plastering', 'Gypsum/Plaster Board/Plastering'), ('Masonry, Tiling', 'Masonry, Tiling'), ('Joinery/Carpentry', 'Joinery/Carpentry'), ('Glazing Works', 'Glazing Works')], max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
