# Generated by Django 4.2.6 on 2023-10-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_career_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='coverletter',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='file',
            field=models.FileField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
