# Generated by Django 4.2.6 on 2023-10-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_career_coverletter_career_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='career'),
        ),
    ]
