# Generated by Django 4.2.6 on 2023-10-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_career_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='file',
        ),
        migrations.AddField(
            model_name='career',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='career/cv/'),
        ),
    ]
