# Generated by Django 4.2.6 on 2023-10-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_career_file_career_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='cv',
            field=models.FileField(default='upload', upload_to='career/cv/'),
            preserve_default=False,
        ),
    ]
