# Generated by Django 4.2.6 on 2023-10-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='coverletter',
            new_name='paragraph',
        ),
    ]
