# Generated by Django 4.2.6 on 2023-10-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
