# Generated by Django 4.2.6 on 2023-10-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='jobrole',
            field=models.CharField(max_length=254),
        ),
    ]
